name: calratio-training
channels:
  - pyviz/label/dev
  - conda-forge
  - defaults

dependencies:
  - holoviews
  - hvplot
  - datashader
  - dask
  - jupyterlab
  - keras
  - nodejs
  - python>=3.7
  - seaborn
  - pip
  - scikit-learn
  - pip:
    - func-adl-xaod
